### ISSUE TITLE
AUTORELEASE: part 2 (publish) error finding artifacts

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#1489]
https://github.com/natcap/invest/actions/runs/7249215793/job/19746747947

The problem may be here:

```
echo "RUN_ID=$( \
    gh run list \
      --branch $VERSION \
      --limit 1 \
      --json databaseId \
      --jq .[].databaseId)" >> $GITHUB_ENV
```

since there are actually 2 jobs that run for the version-tagged commit: 
1. Run Tests and Build
2. Build containers

The next step is referencing the Build containers job:
```
env:
    GITHUB_TOKEN: ***
    VERSION: 3.14.1
    RUN_ID: 7224873090
no valid artifacts found to download
```
https://github.com/natcap/invest/actions/runs/7224873090
